// AUTO-GENERATED by scripts/gen-capability-matrix.ts from bmap-jsapi-dts.
//
// 当前为框架种子版本：手动列出主要能力，待 gen 脚本接入后自动覆盖。
//
// 命名规范（消除歧义）：
// - 类存在性：PascalCase 类名，如 `Prism`、`Marker`、`NavigationControl3D`、`RidingRoute`
// - 类方法/Map 方法：`ClassName.method`，如 `Map.flyTo`、`Map.enableMapClick`、`Marker.openInfoWindow`
// - 这样用户 `caps.has('Map.flyTo')` 一眼能看出是 Map 的 flyTo 方法；
//   `caps.has('Prism')` 能看出是 Prism 类是否存在。

import type { Capability } from '../types';

// ── 4.0+ Map 视角与动画方法 ──
const V4_MAP_VIEW: Capability[] = [
  'Map.flyTo', 'Map.setHeading', 'Map.getHeading', 'Map.setTilt', 'Map.getTilt',
  'Map.startViewAnimation', 'Map.pauseViewAnimation', 'Map.continueViewAnimation', 'Map.cancelViewAnimation',
  'Map.restrictBounds', 'Map.setDisplayOptions', 'Map.setOptions',
  'Map.enableRotate', 'Map.disableRotate', 'Map.enableTilt', 'Map.disableTilt',
  'Map.enableRotateGestures', 'Map.disableRotateGestures',
  'Map.enableTiltGestures', 'Map.disableTiltGestures',
  'Map.enableResizeOnCenter', 'Map.disableResizeOnCenter',
];

// ── 4.0+ 图层类（class 本身存在性） ──
const V4_LAYER_CLASS: Capability[] = [
  'NormalLayer', 'GeoJSONLayer', 'DistrictLayer',
  // 还有：RasterTileLayer / WMSLayer / WMTSLayer / XYZLayer / MVTLayer / PointIconLayer / PointShapeLayer / FillLayer / LineLayer / FeatureLayer / DOMLayer / PanoramaCoverageLayer 等
];

// ── 4.0+ Map 图层方法 ──
const V4_MAP_LAYER: Capability[] = [
  'Map.addNormalLayer', 'Map.removeNormalLayer',
  'Map.addGeoJSONLayer', 'Map.removeGeoJSONLayer',
  'Map.addDistrictLayer', 'Map.removeDistrictLayer',
  'Map.setTrafficOn', 'Map.setTrafficOff',
];

// ── 4.0+ 覆盖物类 ──
const V4_OVERLAY: Capability[] = [
  'Prism', 'Rectangle', 'BezierCurve', 'CustomOverlay', 'GroundPoint',
];

// ── 4.0+ 控件类 ──
const V4_CONTROL: Capability[] = [
  'NavigationControl3D', 'ZoomControl', 'CityListControl', 'LogoControl',
];

// ── 4.0+ 服务类 ──
const V4_SERVICE: Capability[] = [
  'RidingRoute', 'Geolocation', 'LocalCity', 'PlaceDetail',
];

// ── 4.0+ Map 实用方法 ──
const V4_MAP_UTIL: Capability[] = [
  'Map.getMapScreenshot', 'Map.lnglatToMercator', 'Map.mercatorToLnglat',
  'Map.isLoaded', 'Map.getCoordType', 'Map.getMinZoom', 'Map.getMaxZoom',
  'Map.getContainerSize', 'Map.getZoomUnits',
  'Map.addSpots', 'Map.getSpots', 'Map.removeSpots', 'Map.clearSpots', 'Map.hightlightSpotByUid',
  'Map.addLabelsToMapTile', 'Map.removeLabelsFromMapTile',
  'Map.enablePreferredLanguage', 'Map.disablePreferredLanguage',
  'Map.setMapStyleV2',     // 4.0+ 个性化样式 V2
  'Marker.openInfoWindow', // 4.0+ Marker 打开信息窗口
  'Map.destroy',           // 4.0+ 显式销毁
  'Map.checkResize',       // 4.0+ resize API
];

// ── 3.0-only Map 方法 ──
const V3_MAP_ONLY: Capability[] = [
  'Map.enableMapClick', 'Map.disableMapClick',
  'Map.enable3DBuilding', 'Map.disable3DBuilding',
  'Map.highResolutionEnabled',
  'Map.setCurrentCity',
  'Map.setPanorama', 'Map.getPanorama',
  'Map.addHotspot', 'Map.removeHotspot', 'Map.clearHotspots',
  'Map.setMapStyle',       // 3.0-only 个性化样式 V1
  'Map.openInfoWindow',    // 3.0-only map.openInfoWindow（v4 移到 Marker）
  'Map.closeInfoWindow',
  'Map.addTileLayer', 'Map.removeTileLayer', 'Map.getTileLayer',
  'Map.addControl', 'Map.removeControl',
];

// ── 3.0-only 覆盖物 ──
const V3_OVERLAY_ONLY: Capability[] = [
  'Hotspot',   // 仅 3.0
  'PointCollection',   // @removed 4.0
];

// ── 全版本共有（隐式：v3 与 v4 共有） ──
const COMMON: Capability[] = [
  // 基础 Map 命令（全版本）
  'Map.setCenter', 'Map.setZoom', 'Map.centerAndZoom', 'Map.panTo', 'Map.panBy',
  'Map.setViewport', 'Map.getViewport', 'Map.zoomIn', 'Map.zoomOut', 'Map.reset',
  'Map.getCenter', 'Map.getZoom', 'Map.getBounds', 'Map.getSize', 'Map.getDistance',
  'Map.pointToPixel', 'Map.pixelToPoint', 'Map.pointToOverlayPixel', 'Map.overlayPixelToPoint',
  // 交互开关（全版本）
  'Map.enableDragging', 'Map.disableDragging',
  'Map.enableScrollWheelZoom', 'Map.disableScrollWheelZoom',
  'Map.enableDoubleClickZoom', 'Map.disableDoubleClickZoom',
  'Map.enableKeyboard', 'Map.disableKeyboard',
  'Map.enableInertialDragging', 'Map.disableInertialDragging',
  'Map.enableContinuousZoom', 'Map.disableContinuousZoom',
  'Map.enablePinchToZoom', 'Map.disablePinchToZoom',
  'Map.enableAutoResize', 'Map.disableAutoResize',
  'Map.clearOverlays', 'Map.getOverlays', 'Map.addOverlay', 'Map.removeOverlay',
  // 覆盖物（全版本）
  'Marker', 'Label', 'Polyline', 'Polygon', 'Circle',
  'GroundOverlay', 'InfoWindow', 'Symbol', 'Icon', 'IconSequence',
  // 控件（全版本）
  'NavigationControl', 'ScaleControl', 'OverviewMapControl', 'MapTypeControl',
  'CopyrightControl', 'GeolocationControl', 'LocationControl', 'PanoramaControl',
  // 图层（全版本）
  'TileLayer', 'CustomLayer', 'CanvasLayer', 'TrafficLayer',
  // 服务（全版本）
  'LocalSearch', 'Geocoder', 'DrivingRoute', 'WalkingRoute', 'TransitRoute',
  'BusLineSearch', 'Autocomplete', 'Boundary', 'Convertor', 'PanoramaService',
  // 全景（全版本）
  'Panorama', 'PanoramaLabel',
  // 右键菜单
  'ContextMenu', 'MenuItem',
];

const v3Set = new Set<Capability>([...COMMON, ...V3_MAP_ONLY, ...V3_OVERLAY_ONLY]);
const v4Set = new Set<Capability>([
  ...COMMON, ...V4_MAP_VIEW, ...V4_LAYER_CLASS, ...V4_MAP_LAYER, ...V4_OVERLAY, ...V4_CONTROL, ...V4_SERVICE, ...V4_MAP_UTIL,
]);

export const CAPABILITY_MATRIX: Record<'3.0' | '4.0', ReadonlySet<Capability>> = {
  '3.0': v3Set,
  '4.0': v4Set,
};
