// AUTO-GENERATED by scripts/gen-capability-matrix.ts from bmap-jsapi-dts.
//
// 当前为框架种子版本：手动列出主要能力，待 gen 脚本接入后自动覆盖。
//
// 命名规范（消除歧义）：
// - 类存在性：PascalCase 类名，如 `Prism`、`Marker`、`NavigationControl3D`、`RidingRoute`
// - 类方法/Map 方法：`ClassName.method`，如 `Map.flyTo`、`Map.enableMapClick`、`Marker.openInfoWindow`
// - 这样用户 `caps.has('Map.flyTo')` 一眼能看出是 Map 的 flyTo 方法；
//   `caps.has('Prism')` 能看出是 Prism 类是否存在。

import type { Capability } from '../types';

// ── 4.0+ Map 视角与动画方法 ──
const V4_MAP_VIEW: Capability[] = [
  'Map.flyTo', 'Map.setHeading', 'Map.getHeading', 'Map.setTilt', 'Map.getTilt',
  'Map.startViewAnimation', 'Map.pauseViewAnimation', 'Map.continueViewAnimation', 'Map.cancelViewAnimation',
  'Map.restrictBounds', 'Map.setDisplayOptions', 'Map.setOptions',
  'Map.enableRotate', 'Map.disableRotate', 'Map.enableTilt', 'Map.disableTilt',
  'Map.enableRotateGestures', 'Map.disableRotateGestures',
  'Map.enableTiltGestures', 'Map.disableTiltGestures',
  'Map.enableResizeOnCenter', 'Map.disableResizeOnCenter',
];

// ── 4.0+ 图层类（class 本身存在性） ──
const V4_LAYER_CLASS: Capability[] = [
  'NormalLayer', 'GeoJSONLayer', 'DistrictLayer',
  'RasterTileLayer', 'WMSLayer', 'WMTSLayer', 'XYZLayer', 'MVTLayer',
  'FillLayer', 'DOMLayer',
  'PointIconLayer', 'PointShapeLayer',
  'LineLayer', 'PixelLayer', 'BaiduLayer', 'ThreeLayer',
];

// ── 4.0+ Map 图层方法 ──
const V4_MAP_LAYER: Capability[] = [
  'Map.addNormalLayer', 'Map.removeNormalLayer',
  'Map.addGeoJSONLayer', 'Map.removeGeoJSONLayer',
  'Map.addDistrictLayer', 'Map.removeDistrictLayer',
  'Map.setTrafficOn', 'Map.setTrafficOff',
];

// ── 4.0+ 覆盖物类 ──
const V4_OVERLAY: Capability[] = [
  // 注：Rectangle 在源码快照 publicListForMap.js 未导出，但运行时 CDN 版 BMapGL 存在（driver 实测可用）
  'Prism', 'Rectangle', 'BezierCurve', 'CustomOverlay', 'GroundPoint', 'Marker3D', 'SimpleInfoWindow', 'MapMask',
];

// ── 4.0+ 控件类 ──
const V4_CONTROL: Capability[] = [
  'NavigationControl3D', 'ZoomControl', 'LogoControl',
];

// ── 4.0+ 服务类 ──
const V4_SERVICE: Capability[] = [
  'PlaceDetail', 'PlaceDetailPanel',
];

// ── 4.0+ 其他公开类（SDK publicListForMap.js 导出、react-bmap 暂未封装） ──
const V4_MISC: Capability[] = [
  'MapConfig', 'SVGSymbol', 'PolylineMultipart', 'ParkingSpot', 'IndoorManager', 'DistanceTool',
  'Animation', 'ViewAnimation', 'Transitions', 'Event', 'GeoJSONParse', 'Entity', 'DrivingRouteLine', 'XYZProjection',
];

// ── 4.0+ Map 实用方法 ──
const V4_MAP_UTIL: Capability[] = [
  'Map.getScreenshot', 'Map.lnglatToMercator', 'Map.mercatorToLnglat',
  'Map.isLoaded', 'Map.getCoordType', 'Map.getMinZoom', 'Map.getMaxZoom',
  'Map.getContainerSize', 'Map.getZoomUnits',
  'Map.addSpots', 'Map.getSpots', 'Map.removeSpots', 'Map.clearSpots', 'Map.hightlightSpotByUid',
  'Map.addMapLabels', 'Map.removeMapLabels',
  'Map.enablePreferredLanguage', 'Map.disablePreferredLanguage',
  'Map.setMapStyleV2',     // 4.0+ 个性化样式 V2
  'Marker.openInfoWindow', // 4.0+ Marker 打开信息窗口
  'Map.destroy',           // 4.0+ 显式销毁
  'Map.checkResize',       // 4.0+ resize API
];

// ── 3.0-only Map 方法 ──
const V3_MAP_ONLY: Capability[] = [
  'Map.enableMapClick', 'Map.disableMapClick',
  'Map.enable3DBuilding', 'Map.disable3DBuilding',
  'Map.highResolutionEnabled',
  'Map.setCurrentCity',
  'Map.setPanorama', 'Map.getPanorama',
  // Hotspot v4 也支持（publicListForMap.js 导出 + SpotManager）
  'Map.setMapStyle',       // 3.0-only 个性化样式 V1
  'Map.openInfoWindow',    // 3.0-only map.openInfoWindow（v4 移到 Marker）
  'Map.closeInfoWindow',
  'Map.addTileLayer', 'Map.removeTileLayer', 'Map.getTileLayer',
  'Map.addControl', 'Map.removeControl',
];

// ── 3.0-only 覆盖物/图层 ──
const V3_OVERLAY_ONLY: Capability[] = [
  'CustomLayer',           // v4 无此类（对应物是 CustomHtmlLayer/DOMLayer）
  'PanoramaFlashInterface',// v3 publish.js:82 导出，v4 无
];

// ── 全版本共有（隐式：v3 与 v4 共有） ──
const COMMON: Capability[] = [
  // 基础 Map 类（全版本）
  'Map',
  // 基础 Map 命令（全版本）
  'Map.setCenter', 'Map.setZoom', 'Map.centerAndZoom', 'Map.panTo', 'Map.panBy',
  'Map.setViewport', 'Map.getViewport', 'Map.zoomIn', 'Map.zoomOut', 'Map.reset',
  'Map.getCenter', 'Map.getZoom', 'Map.getBounds', 'Map.getSize', 'Map.getDistance',
  'Map.pointToPixel', 'Map.pixelToPoint', 'Map.pointToOverlayPixel', 'Map.overlayPixelToPoint',
  // 交互开关（全版本）
  'Map.enableDragging', 'Map.disableDragging',
  'Map.enableScrollWheelZoom', 'Map.disableScrollWheelZoom',
  'Map.enableDoubleClickZoom', 'Map.disableDoubleClickZoom',
  'Map.enableKeyboard', 'Map.disableKeyboard',
  'Map.enableInertialDragging', 'Map.disableInertialDragging',
  'Map.enableContinuousZoom', 'Map.disableContinuousZoom',
  'Map.enablePinchToZoom', 'Map.disablePinchToZoom',
  'Map.enableAutoResize', 'Map.disableAutoResize',
  'Map.clearOverlays', 'Map.getOverlays', 'Map.addOverlay', 'Map.removeOverlay',
  // 覆盖物（全版本）
  'Overlay', // 公开抽象基类
  'Marker', 'Label', 'Polyline', 'Polygon', 'Circle',
  'GroundOverlay', 'InfoWindow', 'Symbol', 'Icon', 'IconSequence', 'PointCollection',
  'Hotspot',
  // 控件（全版本）
  'Control', // 公开抽象基类
  'NavigationControl', 'ScaleControl', 'OverviewMapControl', 'MapTypeControl',
  'CopyrightControl', 'Copyright', 'GeolocationControl', 'PanoramaControl',
  'CityListControl',
  // 注：LocationControl 的 SDK 类仅 4.0 存在，但 react-bmap 用 GeolocationControl 别名实现，两个版本均可用
  'LocationControl',
  // 图层（全版本）
  'TileLayer', 'TrafficLayer', 'CanvasLayer', 'PanoramaCoverageLayer',
  // 服务（全版本）
  'LocalSearch', 'Geocoder', 'DrivingRoute', 'WalkingRoute', 'TransitRoute',
  'RidingRoute', 'Geolocation', 'LocalCity', 'TruckRoute',
  'BusLineSearch', 'Autocomplete', 'Boundary', 'Convertor', 'PanoramaService', 'RouteSearch',
  // 坐标投影（全版本公开类）
  'Projection', 'MercatorProjection', 'PerspectiveProjection',
  // 全景（全版本）
  'Panorama', 'PanoramaLabel',
  // 右键菜单
  'ContextMenu', 'MenuItem',
];

const v3Set = new Set<Capability>([...COMMON, ...V3_MAP_ONLY, ...V3_OVERLAY_ONLY]);
const v4Set = new Set<Capability>([
  ...COMMON, ...V4_MAP_VIEW, ...V4_LAYER_CLASS, ...V4_MAP_LAYER, ...V4_OVERLAY, ...V4_CONTROL, ...V4_SERVICE, ...V4_MAP_UTIL, ...V4_MISC,
]);

export const CAPABILITY_MATRIX: Record<'3.0' | '4.0', ReadonlySet<Capability>> = {
  '3.0': v3Set,
  '4.0': v4Set,
};
