import type { z } from 'zod';
import {
  MapPropsSchema,
  MarkerPropsSchema,
  MarkerOrderTipPropsSchema,
  InfoWindowPropsSchema,
  CirclePropsSchema,
  PolylinePropsSchema,
  PolygonPropsSchema,
  PointLabelPropsSchema,
  NavigationControlPropsSchema,
  OverviewMapControlPropsSchema,
  ScaleControlPropsSchema,
  MapTypeControlPropsSchema,
  PanoramaControlPropsSchema,
  GeolocationControlPropsSchema,
  TrafficLayerPropsSchema,
  MapvLayerPropsSchema,
  MapvglLayerPropsSchema,
  MapvglViewPropsSchema,
  DrivingRoutePropsSchema,
  WalkingRoutePropsSchema,
  AutocompletePropsSchema,
  RoadPropsSchema,
  BoundaryPropsSchema,
  MarkerListPropsSchema,
  MapvMarkerListPropsSchema,
  ArcPropsSchema,
  ThickRayPropsSchema,
  MapListenerPropsSchema,
} from 'react-bmap';

export const schemaMap: Record<string, z.ZodObject<z.ZodRawShape>> = {
  map: MapPropsSchema,
  marker: MarkerPropsSchema,
  markerordertip: MarkerOrderTipPropsSchema,
  infowindow: InfoWindowPropsSchema,
  circle: CirclePropsSchema,
  polyline: PolylinePropsSchema,
  polygon: PolygonPropsSchema,
  pointlabel: PointLabelPropsSchema,
  navigationcontrol: NavigationControlPropsSchema,
  overviewmapcontrol: OverviewMapControlPropsSchema,
  scalecontrol: ScaleControlPropsSchema,
  maptypecontrol: MapTypeControlPropsSchema,
  panoramacontrol: PanoramaControlPropsSchema,
  geolocationcontrol: GeolocationControlPropsSchema,
  trafficlayer: TrafficLayerPropsSchema,
  mapvlayer: MapvLayerPropsSchema,
  mapvglayer: MapvglLayerPropsSchema,
  mapvglview: MapvglViewPropsSchema,
  drivingroute: DrivingRoutePropsSchema,
  walkingroute: WalkingRoutePropsSchema,
  autocomplete: AutocompletePropsSchema,
  road: RoadPropsSchema,
  boundary: BoundaryPropsSchema,
  markerlist: MarkerListPropsSchema,
  mapvmarkerlist: MapvMarkerListPropsSchema,
  arc: ArcPropsSchema,
  thickray: ThickRayPropsSchema,
  maplistener: MapListenerPropsSchema,
};
